### PR TITLE
ci: update setup-ghidra

### PR DESCRIPTION
**Pull request by antoniovazquezblanco**

### CODE REVIEW

**Comment by antoniovazquezblanco** [comment]
That is optional. You may not pass it but if you run a lot of jobs consecutively you may hit API rate limiting.

I will remove it. If you ever hit API rate limiting it is just a matter of adding it back. :)

**Comment by antoniovazquezblanco** [comment]
Done :)

**Comment by kotcrab** [comment]
Thanks, I've never hit limits with the old plugins so I'd rather avoid it. 
CI has failed though, seems like it's required.

**Comment by antoniovazquezblanco** [comment]
Oh, it is not intended to be mandatory but I always pass the token. This is useful testing for me. I will find some time to look into it, fix it and get back to the PR. I will mark as a draft for the time being.

Thanks for the patience!

**Comment by antoniovazquezblanco** [comment]
Found some time to do this :)

**Comment by kotcrab** [comment]
Awesome looks like it works now. Can you update the publish workflow too?

**Comment by antoniovazquezblanco** [comment]
Oops. Done!

BTW, you may be able to condense both files into one by using an "if" parameter in the publish step to check for tag pushes... :)

**Comment by kotcrab** [comment]
Thanks!

Yeah, that's a good idea, I'll look into it.

**Pull request merged**
