### PR TITLE
Use Ghidra's Gradle scripts for packaging the extension

### PR DESCRIPTION
**Pull request by rndtrash**
Ghidra 10.4 didn't like the .zip from releases, and since I use a Flatpak version of Ghidra, I can't modify the installation that easily, so I changed the Gradle script to use Ghidra's tasks for packaging, and now it makes packages that can be installed in Ghidra (`./gradlew buildExtension`). Though I'm not sure if I didn't miss anything important, it's my first time writing Gradle scripts *and* my first time using this extension :P

image
image
[ghidra_10.4_FLATPAK_20231104_ghidra-allegrex.zip](https://github.com/kotcrab/ghidra-allegrex/files/13257434/ghidra_10.4_FLATPAK_20231104_ghidra-allegrex.zip)

### CODE REVIEW

**Comment by Nemoumbra** [comment]
Oh, so the problem is with a specific install of Ghidra 10.4 that doesn't let you access its `ghidra_10.4_PUBLIC\Ghidra\Processors` dir?

**Comment by rndtrash** [comment]
Well, more like the whole Ghidra folder is read-only.

**Comment by kotcrab** [comment]
Sorry but this can't be merged in this form as you've removed important stuff for the development and CI workflows.
I have this partially done in [my other extension](https://github.com/kotcrab/ghidra-rest-api) I'm working on but CI is still on the to do list.

This covers issue #8.

**Comment by rndtrash** [comment]
I can fix the CI workflow if you want, seems as easy as replacing `ghidraInstallThenPackage` with `buildExtension` and `build/dist` with just the `dist`.

About the important development stuff, what's missing?

**Comment by kotcrab** [comment]
The `ghidraInstall*` tasks are important for development, they are described in the README (which will also need updating).
Don't want to discourage you but I'll want to have this unified with my other extension repo so my plan is to do it there then port changes here.
Though it's good we have some way for building it the standard way for people for need it so this can stay open.

**Comment by rndtrash** [comment]
It's alright, I just wanted to build this extension, no pressure 🙂👍🏻

**Comment by kotcrab** [comment]
I've done the required changes for this on the master branch so closing this PR.

**Pull request closed without merging**
